entity.7=minecraft:sheep naturalist:boar naturalist:bluejay naturalist:butterfly naturalist:canary naturalist:cardinal naturalist:caterpillar naturalist:robin naturalist:finch naturalist:bass naturalist:catfish naturalist:duck naturalist:elephant naturalist:firefly naturalist:giraffe naturalist:hippopotamus naturalist:zebra
entity.8=minecraft:name_tag
entity.9=minecraft:entity_shadow
entity.10=minecraft:entity_flame
