item.12=minecraft:torch minecraft:soul_torch minecraft:lantern minecraft:soul_lantern
item.20=minecraft:iron_boots
item.21=minecraft:iron_leggings
item.22=minecraft:iron_chestplate
item.23=minecraft:iron_helmet
