separateEntityDraws=true
sliders=REFERENCE_QUALITY
profile.default=!REFERENCE_PROFILE REFERENCE_QUALITY=1
profile.validation=REFERENCE_PROFILE REFERENCE_QUALITY=2
screen=[profile] REFERENCE_QUALITY [advanced]
screen.columns=2
screen.advanced=REFERENCE_PROFILE
screen.advanced.columns=1
