# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:armor_stand_minimal"
data modify storage animated_java:temp entry.data.rig_hash set value "3224f423d0f9622aec7ae9e612fd8322b4ed29a61f4846d67b7706aab6f430a3"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.armor_stand_minimal.node.baseplate_pivot_a] run function aj:armor_stand_minimal/zzz/summon/as_node/baseplate_pivot_a
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.baseplate_pivot_a set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.armor_stand_minimal.node.head] run function aj:armor_stand_minimal/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.armor_stand_minimal.node.left_arm] run function aj:armor_stand_minimal/zzz/summon/as_node/left_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.armor_stand_minimal.node.right_arm] run function aj:armor_stand_minimal/zzz/summon/as_node/right_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.armor_stand_minimal.node.body] run function aj:armor_stand_minimal/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.armor_stand_minimal.node.left_leg] run function aj:armor_stand_minimal/zzz/summon/as_node/left_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_leg set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.armor_stand_minimal.node.right_leg] run function aj:armor_stand_minimal/zzz/summon/as_node/right_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_leg set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:armor_stand_minimal/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:armor_stand_minimal/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:armor_stand_minimal/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run tp @s ~ ~ ~ ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new