shadowTerrain=false
shadowTranslucent=false
shadowEntities=false

#if SHADOW_CASTER_MODE == 1
shadowPlayer=true
shadowBlockEntities=false
shadowLightBlockEntities=false
#elif SHADOW_CASTER_MODE == 2
shadowPlayer=false
shadowBlockEntities=false
shadowLightBlockEntities=true
#else
shadowPlayer=false
shadowBlockEntities=true
shadowLightBlockEntities=false
#endif
