# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:armor_stand_minimal rig_hash set value '3224f423d0f9622aec7ae9e612fd8322b4ed29a61f4846d67b7706aab6f430a3'
scoreboard objectives add aj.walk.frame dummy