name = "Minosoft Content Fidelity Compatibility Ladder"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4668271f336ce648baf3b463208c559beb0202796116ef0a824da20aadc2782d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
