name = "Minosoft Content Fidelity Compatibility Ladder"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9db05e666357221589237140faae8e97d07f35c5d8278c2b9cca606b254142d8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
