name = "Minosoft Content Fidelity Compatibility Ladder"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "926a13c2098b62114bf89981ecbf0a9893055b976479beb7e3fc0bcf0657d421"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
