# Copyright (C) 2026 Jacob Repp

name = "Minosoft Distant Horizons + Bliss"
pack-format = "packwiz:1.1.0"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d8c533ca1e32743cf0c3cdc159aa8913f8fafdd11a5955c5cadf18c30ea26c0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
