# Copyright (C) 2026 Jacob Repp

name = "Minosoft Distant Horizons + Bliss"
pack-format = "packwiz:1.1.0"
version = "0.1.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d6b459ffe979a42d450ba57fa8b8679f73c8a512d98a5f8c23c336d1fbb94c8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
