# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function aj:armor_stand_minimal/animations/walk/zzz/frames/$(frame) with storage animated_java:temp entry.data.uuids_by_name
execute on passengers run data modify entity @s start_interpolation set value -1
return 1