# Copyright (C) 2026 Jacob Repp

name = "Minosoft Sodium Compatibility Ladder"
pack-format = "packwiz:1.1.0"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dad20fba9b9539d118fa1b8c53682ed194fc00c1cc90285ed0eb7dd9a2a84f1f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
