# Copyright (C) 2026 Jacob Repp

name = "Minosoft Fabric Compatibility Stack"
pack-format = "packwiz:1.1.0"
version = "0.8.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e42521ae207821f4a81ea799e1c271379e25c1126364e3d1ba832de00a572294"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
