# Copyright (C) 2026 Jacob Repp

name = "Minosoft Fabric Compatibility Stack"
pack-format = "packwiz:1.1.0"
version = "0.6.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8dcb86af76406e71dd13b877f5ee2a27e40d1e674af817f731bae1de5f1f3cd"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
